// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: plugin_permission.proto

package zelligo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionType int32

const (
	PermissionType_ReadApplicationState   PermissionType = 0
	PermissionType_ChangeApplicationState PermissionType = 1
	PermissionType_OpenFiles              PermissionType = 2
	PermissionType_RunCommands            PermissionType = 3
	PermissionType_OpenTerminalsOrPlugins PermissionType = 4
	PermissionType_WriteToStdin           PermissionType = 5
)

// Enum value maps for PermissionType.
var (
	PermissionType_name = map[int32]string{
		0: "ReadApplicationState",
		1: "ChangeApplicationState",
		2: "OpenFiles",
		3: "RunCommands",
		4: "OpenTerminalsOrPlugins",
		5: "WriteToStdin",
	}
	PermissionType_value = map[string]int32{
		"ReadApplicationState":   0,
		"ChangeApplicationState": 1,
		"OpenFiles":              2,
		"RunCommands":            3,
		"OpenTerminalsOrPlugins": 4,
		"WriteToStdin":           5,
	}
)

func (x PermissionType) Enum() *PermissionType {
	p := new(PermissionType)
	*p = x
	return p
}

func (x PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_permission_proto_enumTypes[0].Descriptor()
}

func (PermissionType) Type() protoreflect.EnumType {
	return &file_plugin_permission_proto_enumTypes[0]
}

func (x PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionType.Descriptor instead.
func (PermissionType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_permission_proto_rawDescGZIP(), []int{0}
}

var File_plugin_permission_proto protoreflect.FileDescriptor

var file_plugin_permission_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x2a, 0x94, 0x01, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x1a, 0x0a,
	0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x70, 0x65,
	0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x10, 0x03, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x70, 0x65,
	0x6e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x73, 0x4f, 0x72, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x73, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x6f,
	0x53, 0x74, 0x64, 0x69, 0x6e, 0x10, 0x05, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_permission_proto_rawDescOnce sync.Once
	file_plugin_permission_proto_rawDescData = file_plugin_permission_proto_rawDesc
)

func file_plugin_permission_proto_rawDescGZIP() []byte {
	file_plugin_permission_proto_rawDescOnce.Do(func() {
		file_plugin_permission_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_permission_proto_rawDescData)
	})
	return file_plugin_permission_proto_rawDescData
}

var file_plugin_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_permission_proto_goTypes = []interface{}{
	(PermissionType)(0), // 0: api.plugin_permission.PermissionType
}
var file_plugin_permission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_permission_proto_init() }
func file_plugin_permission_proto_init() {
	if File_plugin_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_permission_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_permission_proto_goTypes,
		DependencyIndexes: file_plugin_permission_proto_depIdxs,
		EnumInfos:         file_plugin_permission_proto_enumTypes,
	}.Build()
	File_plugin_permission_proto = out.File
	file_plugin_permission_proto_rawDesc = nil
	file_plugin_permission_proto_goTypes = nil
	file_plugin_permission_proto_depIdxs = nil
}
