// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: resize.proto

package zelligo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResizeAction int32

const (
	ResizeAction_Increase ResizeAction = 0
	ResizeAction_Decrease ResizeAction = 1
)

// Enum value maps for ResizeAction.
var (
	ResizeAction_name = map[int32]string{
		0: "Increase",
		1: "Decrease",
	}
	ResizeAction_value = map[string]int32{
		"Increase": 0,
		"Decrease": 1,
	}
)

func (x ResizeAction) Enum() *ResizeAction {
	p := new(ResizeAction)
	*p = x
	return p
}

func (x ResizeAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResizeAction) Descriptor() protoreflect.EnumDescriptor {
	return file_resize_proto_enumTypes[0].Descriptor()
}

func (ResizeAction) Type() protoreflect.EnumType {
	return &file_resize_proto_enumTypes[0]
}

func (x ResizeAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResizeAction.Descriptor instead.
func (ResizeAction) EnumDescriptor() ([]byte, []int) {
	return file_resize_proto_rawDescGZIP(), []int{0}
}

type ResizeDirection int32

const (
	ResizeDirection_Left  ResizeDirection = 0
	ResizeDirection_Right ResizeDirection = 1
	ResizeDirection_Up    ResizeDirection = 2
	ResizeDirection_Down  ResizeDirection = 3
)

// Enum value maps for ResizeDirection.
var (
	ResizeDirection_name = map[int32]string{
		0: "Left",
		1: "Right",
		2: "Up",
		3: "Down",
	}
	ResizeDirection_value = map[string]int32{
		"Left":  0,
		"Right": 1,
		"Up":    2,
		"Down":  3,
	}
)

func (x ResizeDirection) Enum() *ResizeDirection {
	p := new(ResizeDirection)
	*p = x
	return p
}

func (x ResizeDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResizeDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_resize_proto_enumTypes[1].Descriptor()
}

func (ResizeDirection) Type() protoreflect.EnumType {
	return &file_resize_proto_enumTypes[1]
}

func (x ResizeDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResizeDirection.Descriptor instead.
func (ResizeDirection) EnumDescriptor() ([]byte, []int) {
	return file_resize_proto_rawDescGZIP(), []int{1}
}

type Resize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResizeAction ResizeAction     `protobuf:"varint,1,opt,name=resize_action,json=resizeAction,proto3,enum=api.resize.ResizeAction" json:"resize_action,omitempty"`
	Direction    *ResizeDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=api.resize.ResizeDirection,oneof" json:"direction,omitempty"`
}

func (x *Resize) Reset() {
	*x = Resize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resize_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_resize_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_resize_proto_rawDescGZIP(), []int{0}
}

func (x *Resize) GetResizeAction() ResizeAction {
	if x != nil {
		return x.ResizeAction
	}
	return ResizeAction_Increase
}

func (x *Resize) GetDirection() ResizeDirection {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return ResizeDirection_Left
}

type MoveDirection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction ResizeDirection `protobuf:"varint,1,opt,name=direction,proto3,enum=api.resize.ResizeDirection" json:"direction,omitempty"`
}

func (x *MoveDirection) Reset() {
	*x = MoveDirection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resize_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveDirection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDirection) ProtoMessage() {}

func (x *MoveDirection) ProtoReflect() protoreflect.Message {
	mi := &file_resize_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDirection.ProtoReflect.Descriptor instead.
func (*MoveDirection) Descriptor() ([]byte, []int) {
	return file_resize_proto_rawDescGZIP(), []int{1}
}

func (x *MoveDirection) GetDirection() ResizeDirection {
	if x != nil {
		return x.Direction
	}
	return ResizeDirection_Left
}

var File_resize_proto protoreflect.FileDescriptor

var file_resize_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65,
	0x73, 0x69, 0x7a, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x0d, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73,
	0x69, 0x7a, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x2a,
	0x0a, 0x0c, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c,
	0x0a, 0x08, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x44, 0x65, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x10, 0x01, 0x2a, 0x38, 0x0a, 0x0f, 0x52, 0x65,
	0x73, 0x69, 0x7a, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a,
	0x04, 0x4c, 0x65, 0x66, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x69, 0x67, 0x68, 0x74,
	0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x70, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x6f,
	0x77, 0x6e, 0x10, 0x03, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resize_proto_rawDescOnce sync.Once
	file_resize_proto_rawDescData = file_resize_proto_rawDesc
)

func file_resize_proto_rawDescGZIP() []byte {
	file_resize_proto_rawDescOnce.Do(func() {
		file_resize_proto_rawDescData = protoimpl.X.CompressGZIP(file_resize_proto_rawDescData)
	})
	return file_resize_proto_rawDescData
}

var file_resize_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_resize_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resize_proto_goTypes = []interface{}{
	(ResizeAction)(0),     // 0: api.resize.ResizeAction
	(ResizeDirection)(0),  // 1: api.resize.ResizeDirection
	(*Resize)(nil),        // 2: api.resize.Resize
	(*MoveDirection)(nil), // 3: api.resize.MoveDirection
}
var file_resize_proto_depIdxs = []int32{
	0, // 0: api.resize.Resize.resize_action:type_name -> api.resize.ResizeAction
	1, // 1: api.resize.Resize.direction:type_name -> api.resize.ResizeDirection
	1, // 2: api.resize.MoveDirection.direction:type_name -> api.resize.ResizeDirection
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resize_proto_init() }
func file_resize_proto_init() {
	if File_resize_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resize_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resize_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveDirection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_resize_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resize_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resize_proto_goTypes,
		DependencyIndexes: file_resize_proto_depIdxs,
		EnumInfos:         file_resize_proto_enumTypes,
		MessageInfos:      file_resize_proto_msgTypes,
	}.Build()
	File_resize_proto = out.File
	file_resize_proto_rawDesc = nil
	file_resize_proto_goTypes = nil
	file_resize_proto_depIdxs = nil
}
